/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CameraCapture: typeof import('./src/components/CameraCapture.vue')['default']
    DeleteDialog: typeof import('./src/components/ui/DeleteDialog.vue')['default']
    InternForm: typeof import('./src/components/InternForm.vue')['default']
    InternList: typeof import('./src/components/InternList.vue')['default']
    LayoutWrapper: typeof import('./src/components/layouts/LayoutWrapper.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Pagination: typeof import('./src/components/ui/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
