/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InternForm: typeof import('./src/components/InternForm.vue')['default']
    InternList: typeof import('./src/components/InternList.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
